---
title: "Untitled"
author: "Robert A. Stevens"
date: "6/5/2018"
output: html_document
---

These are for Chapter 3?

```{octave}
% "carUpdate"

aRate = 0.05; % Rate of cars in Albany dropped off in Boston
bRate = 0.03; % Rate of cars in Boston dropped off in Albany

aMove = round(aRate * a); % Number of cars moved from Albany to Boston
bMove = round(bRate * b); % Number of cars moved from Boston to Albany

a = a - aMove + bMove % Number of cars remaining in Albany
b = b - bMove + aMove % Number of cars remaining in Boston

a = 150 % initial number of cars in Albany
b = 150 % initial number of cars in Boston

carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
carUpdate
```

```{octave}
% "car_update"

aRate = 0.05; % Rate of cars in Albany dropped off in Boston
bRate = 0.03; % Rate of cars in Boston dropped off in Albany

atob = round(aRate*a - bRate*b); % Number of cars moved from Albany to Boston

a = a - atob % Number of cars remaining in Albany
b = b + atob % Number of cars remaining in Boston
```

```{r}
# "carUpdate"

aRate <- 0.05 # Rate of cars in Albany dropped off in Boston
bRate <- 0.03 # Rate of cars in Boston dropped off in Albany

aMove <- round(aRate * a) # Number of cars moved from Albany to Boston
bMove <- round(bRate * b) # Number of cars moved from Boston to Albany

a <- a - aMove + bMove # Number of cars remaining in Albany
b <- b - bMove + aMove # Number of cars remaining in Boston

print(a)
print(b)

a <- 150 # initial number of cars in Albany
b <- 150 # initial number of cars in Boston

source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")
source("carUpdate.R")

```

```{r}
# "car_update"
aRate <- 0.05 # Rate of cars in Albany dropped off in Boston
bRate <- 0.03 # Rate of cars in Boston dropped off in Albany

atob <- round(aRate*a - bRate*b) # Number of cars moved from Albany to Boston

print(a <- a - atob) # Number of cars remaining in Albany
print(b <- b + atob) # Number of cars remaining in Boston
```


```{python}
# "carUpdate"
aRate = 0.05 # Rate of cars in Albany dropped off in Boston
bRate = 0.03 # Rate of cars in Boston dropped off in Albany

aMove = round(aRate * a) # Number of cars moved from Albany to Boston
bMove = round(bRate * b) # Number of cars moved from Boston to Albany

a = a - aMove + bMove # Number of cars remaining in Albany
b = b - bMove + aMove # Number of cars remaining in Boston

print "a = ", a
print "b = ", b

import sys

a = 150 # initial number of cars in Albany
b = 150 # initial number of cars in Boston

sys.argv = ['carUpdate.py', 'a', 'b']
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
execfile('carUpdate.py')
```

```{python}
# "car_update"

aRate = 0.05 # Rate of cars in Albany dropped off in Boston
bRate = 0.03 # Rate of cars in Boston dropped off in Albany

atob = round(aRate*a - bRate*b) # Number of cars moved from Albany to Boston

a = a - atob # Number of cars remaining in Albany
b = b + atob # Number of cars remaining in Boston

print "a = ", a
print "b = ", b
```
