---
title: "Physical Modeling in MATLAB"
author: "Robert A. Stevens"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

by Allen B. Downey 

Version 1.1.8

# Preface

Most books that use MATLAB are aimed at readers who know how to program. This book is for people who have never programmed before.

As a result, the order of presentation is unusual. The book starts with scalar values and works up to vectors and matrices very gradually. This approach is good for beginning programmers, because it is hard to understand composite objects until you understand basic programming semantics. But there are problems:

- The MATLAB documentation is written in terms of matrices, and so are the error messages. To mitigate this problem, the book explains the necessary vocabulary early and deciphers some of the messages that beginners find confusing.

- Many of the examples in the first half of the book are not idiomatic MATLAB. I address this problem in the second half by translating the examples into a more standard style.

The book puts a lot of emphasis on functions, in part because they are an important mechanism for controlling program complexity, and also because they are useful for working with MATLAB tools like fzero and ode45.

I assume that readers know calculus, differential equations, and physics, but not linear algebra. I explain the math as I go along, but the descriptions might not be enough for someone who hasn’t seen the material before.

There are small exercises within each chapter, and a few larger exercises at the end of some chapters.

If you have suggestions and corrections, please send them to downey@allendowney.com.

Allen B. Downey, Needham, MA
 
# Contents

00\. Preface

01\. Variables and values

02\. Scripts

03\. Loops

04\. Vectors

05\. Functions

06\. Zero-finding 

07\. Functions of vectors 

08\. Ordinary Differential Equations 

09\. Systems of ODEs 

10\. Second-order systems 

11\. Optimization and Interpolation 

12\. Vectors as vectors
